# Generated by Django 3.2 on 2021-04-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('brand_logo', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('width', models.FloatField(default=0)),
                ('depth', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
            ],
        ),
    ]
